cloud infrastrucutre notes
giacomodeliberali/ict-infrastructures pull request #20
Opened 2019-06-28 16:40 UTC by bongi23

Hello! I have merged my notes about cloud infrastructures. Please take a look and give me a feedback :)

2019-06-30 09:17 UTC, bongi23 commented
I forgot to say that there are some "TODO" here and there, but they almost all refer to adding some images.

2019-06-30 11:39 UTC, daquinoaldo approved these changes

2019-06-30 12:18 UTC, giacomodeliberali requested changes
Before merging please run:
- `npm run contributors:add bongi23 doc`: to add yourself as contributor
- `npm install && npm run toc && npm run toc:git:add` in order to properly update the table of contents. Thanks 👍

2019-07-01 17:24 UTC, daquinoaldo approved these changes

2019-07-01 17:24 UTC, merged